### ISSUE TITLE
Content analysis 2.0 overview issue

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#1296]
## New checks
- [x] Implement taxonomy internal linking assessment https://github.com/Yoast/wordpress-seo/issues/9076
  -  [x] Convert internal linking assessment to class 
  -  [x] Change assessment calls in taxonomy assessor https://github.com/Yoast/wordpress-seo/issues/9697
https://github.com/Yoast/YoastSEO.js/issues/1439
- [x] Implement single H1 assessment #1298 
- [ ]  Implement file size assessment #1302
- [x]  Implement keyword distribution assessment #1314 

## Alterations to existing checks
- [x] Change boundaries of taxonomy text length assessment #1300, moved to https://github.com/Yoast/wordpress-seo/issues/8986
- [x] Change boundaries of outbound links assessment #1301
- [x] Change boundaries of meta description keyword assessment #1308 
- [x] Improve keyword density assessment #1309 
- [x] Improve feedback for previously used keywords assessment #1310 (has already been fixed)
- [x] Improve keyword in subheadings assessment #1311 
- [x] Improve keyphrase length assessment #1312 
- [x]  Improve the keyword in title assessment #1313
  - [x] Also change in taxonomy assessor https://github.com/Yoast/wordpress-seo/issues/9630
- [x] Penalize image anchor text over-optimization #1388 **wait for class refactoring to be merged**

## To be removed
_These assessments can be removed once the following PR has been merged: https://github.com/Yoast/YoastSEO.js/pull/1433 (since this PR change the assessor spec)_ -> has been merged
- [x] Remove stopword in focus keyword check #1320  
- [x] Remove length of URL check #1319 
- [x] Remove stopword in slug check #1318 
  - [x] Also remove these from the taxonomy assessor https://github.com/Yoast/wordpress-seo/issues/9512
- [x] Close the following issues as irrelevant: https://github.com/Yoast/YoastSEO.js/issues/353

## Notifications
- [x] Implement stale content notification Yoast/wordpress-seo/issues/8309

## Miscellaneous
- [x] ~~We should make sure that all assessments are accompanied by explanation links https://github.com/Yoast/YoastSEO.js/issues/1493~~ implemented in 9.0
- [ ] ~~Focus keyword prompt needs to be made more descriptive https://github.com/Yoast/wordpress-seo/issues/9578~~ obsolete
- [x] ~~Create secondary keyword assessor #1479 and~~
  - [x] ~~Call the secondary keyword assessor for multiple keywords in Premium https://github.com/Yoast/wordpress-seo-premium/issues/1743~~ implemented in 9.0
- [ ] Add new assessments to taxonomy assessor https://github.com/Yoast/wordpress-seo/issues/9591

## Bugs
- [x] Meta description keyword assessment gives incorrect feedback https://github.com/Yoast/YoastSEO.js/issues/1478
  - [x] Also change taxonomy assessor specs https://github.com/Yoast/wordpress-seo/issues/9718

## Post-morphology

Complete overview:

| Feature                                                  | What needs to be done                                                                                                                                                                                                         |
|----------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Keyword in subheadings                                   | Think of new boundaries                                                                                                                                                 |
| Keyword in meta description                              | Use develop version (develop version incorporates changes from recalibration))                                                                                                                                                |
| Keyphrase density                                        | Use develop version; should we still incorporate the length of the keyphrase (/the number of content words in the keyphrase) when calculating density?                                                                        |
| Keyphrase in subheadings                                 | Think of new boundaries                                                                                                                                                |
| Keyphrase length                                         | Use develop version (develop version incorporates changes from recalibration)                                                                                                                                                 |
| Keyword distribution                                     | Use develop version (develop version incorporates changes from recalibration)                                                                                                                                                 |
| Stopwords in keyphrase                                   | Removed in both                                                                                                                                                                                                               |
| Single H1 assessment                                     | Use recalibration version (not influenced by morphology); feedback strings need to be changed to new format                                                                                                                   |
| Stale content notification                               | New in recalibration (in WordPress SEO)                                                                                                                                                                                       |
| Length URL                                               | Removed in recalibration                                                                                                                                                                                                      |
| Stopwords in slug                                        | Removed in recalibration                                                                                                                                                                                                      |
| Outbound links                                           | Some small changes in develop; should use new boundaries from recalibration                                                                                                                                                   |
| Keyphrase in title                                       | Mix of develop and recalibration; use develop way of matching keyphrases and add stripping of function words at beginning and make sure that the assessment is only triggered when a title has been set                       |
| Keyword in images                                        | Mix of develop and recalibration; use develop way of matching keyphrases and add functionality from recalibration that checks how many matches there are                                                                      |
| Taxonomy text length                                     | Make sure the taxonomy assessor uses the text length assessment instead of the taxonomy text length assessment; it should also pass the correct boundaries (see here: https://github.com/Yoast/wordpress-seo/pull/9001/files) |
| Taxonomy assessor                                        | Add all new assessments; delete taxonomy assessor in WordPress SEO also on develop                                                                                                                                            |
| ~~Focus keyphrase prompt needs to be made more descriptive~~ | Obsolete                                                                                                                                                                                                 |
| File size assessment                                     | Still needs to be implemented                                                                                                                                                                                                 |

**Comment by manuelaugustin** [comment]
## To do (based on above list):

- [x] Work out a way to incorporate keyphrase length in the new keyphrase density assessment #1924
- [x] Add Single H1 assessment from old recalibration branch and change the feedback texts to match the new format; add also to taxonomy assessor #1926 
- [x] Add stale content filter (implemented in wordpress-seo; should be switched on and off with the recalibration toggle) - see toggle issue: https://github.com/Yoast/wordpress-seo/issues/11450
- [x] Keyphrase in subheadings - new boundaries were rejected as too strict in the morphology release; how can we improve this? (perhaps look at level of headings?; needs more investigation & decision) #1946
- [x] Remove URL length assessment #1927
- [x] Remove stopwords in slug assessment #1928
- [x] Use new boundaries from recalibration branch for the outbound links assessment #1929 
- [x] Keyphrase in title: ignore function words at the beginning of the title; make sure the assessment is only triggered when a title has been set #1947
- [x] Images keyphrase: add functionality from recalibration that checks how many matches there are #1938 
- [x] Taxonomy text length: Make sure the taxonomy assessor uses the text length assessment instead of the taxonomy text length assessment; it should also pass the correct boundaries (see here: https://github.com/Yoast/wordpress-seo/pull/9001/files) #1939
- [x] Check whether the focus keyphrase prompt still should get designed as outlined here: https://github.com/Yoast/wordpress-seo/issues/9578 --> obsolete
- [ ] Implement file size assessment https://github.com/Yoast/YoastSEO.js/issues/1302

## Morphology recalibration issues (stretch goals)
- [x] Keyphrase length: change boundaries for languages where we don't have function word support https://github.com/Yoast/YoastSEO.js/issues/1965
- [x] Keyphrase in subheading: change matching criterion for languages without function word support https://github.com/Yoast/YoastSEO.js/issues/1966

## Documentation/external communication
- [ ] Keep the Scoring SEO analysis wiki (https://github.com/Yoast/YoastSEO.js/wiki/Scoring-SEO-analysis) up-to-date. For all assessments that have been changed, the new functionality should be added next to the old functionality (It's probably best to make a copy, e.g. `3a) Keyword density reclibrated`) 
- [ ] Make a list of all changes/new assessments and communicate them to the blog team so that they can create content.
  * Keyphrase density changed to take into account the length of the keyphrase
  * New assessment: Single H1 assessment

## Stretch goals
- [ ] Refactor single title assessment https://github.com/Yoast/YoastSEO.js/issues/1964

**Comment by IreneStr** [comment]
The recalibration has been shipped 🎉
