### ISSUE TITLE
Russian module for the Readability analysis: overview issue

### ISSUE THREAD

**Issue by nataliashitova** [Yoast/YoastSEO.js#1437]
### New assessments (Russian module) for the Readability analysis (branch feature/russian)

- [x] Add transition word assessment for Russian #1431  #1432 
- [x] Add sentence length assessment for Russian #1434  #1436  
- [x] Add Flesch reading ease assessment for Russian #1438 #1442
- [x] Add sentence beginnings assessment for Russian #1443 #1445
- [x] Add internal linking for Russian #1455 #1459 
- [x] Add passive voice assessment for Russian #1447 #1456 #1458

**Comment by nataliashitova** [comment]
Development is done. All remaining issues with the readability analysis of Russian will be listed and addressed in #1461.
