### ISSUE TITLE
Overview issue: Implement synonyms analysis for topic density and topic distribution assessments

### ISSUE THREAD

**Issue by nataliashitova** [Yoast/YoastSEO.js#1547]
**In Free & Premium:**
* Add keyword distribution from recalibration

**In Premium:**
* Topic density & topic distribution assessments
* These should replace keyword distribution & keyword density when synonyms have been added
* The density and distribution boundaries need to be stricter when synonyms are used
* Add a synonyms input field (comma-separated)

**What do we need?**
* An input field for synonyms
* Synonyms need to be fetched from the input field (via post scraper)
* Synonyms need to be added to Paper
* Assessment architecture (for kw distribution and density) needs to support arrays

**To do:**
- [x] Make issue for design team to make the input field https://github.com/Yoast/wordpress-seo-premium/issues/1796

- [x] Adapt Paper.js (incl. getSynonyms, hasSynonyms) #1541
- [x] Make a keyword parser that transforms the keyword into an array #1542
- [x]  Make a topicDensity research #1544 
- [x] Copy the keyword distribution research to the feature/synonyms branch #1545
- [x]  Make a topicDistribution research #1546
- [x]  Increase boundaries in topicDistribution by 0.5% #1562
- [x] Implement the input field together with the backend-team #1564, https://github.com/Yoast/yoast-components/pull/625, https://github.com/Yoast/wordpress-seo-premium/pull/1817
- [x]  Create a premium SEOAssessor #1543 
- [x] Final changes (once the UI is in place) #1565
  - Change `isApplicable` conditions of assessments:
    - topicDensityAssessment
    - keyWordDensity
    - Change `topicCountSpec` & `topicDensitySpec`
    - Final run through all todo comments in the feature branch
    - Add links to kb article to the feedback strings

**Comment by nataliashitova** [comment]
Project finished.
