### ISSUE TITLE
Polish module for readability analysis: overview issue

### ISSUE THREAD

**Issue by agnieszkaszuba** [Yoast/YoastSEO.js#1551]
### New assessments for Polish readability analysis (branch: feature/polish)

- [x] Add Polish transition word assessment #1528 , #1529 
- [x] Add Polish internal linking for Polish #1530, #1539 
- [x] Add Polish internal linking in premium 
- [x] Add sentence length limit for Polish #1622 #1627 
- [x] Add sentence beginnings assessment #1631 #1629
- [x] Add passive voice assessment for Polish #1628 #1614
- [x] Add Polish to overview table in readme, see e.g. https://github.com/Yoast/YoastSEO.js/pull/1520
