### ISSUE TITLE
Overview: Webworker

### ISSUE THREAD

**Issue by igorschoester** [Yoast/YoastSEO.js#1616]
The mastermind issue: https://github.com/Yoast/YoastSEO.js/issues/1571
Branch: `feature/webworker`

### MVP
- [ ] Take the time to talk about the naming with the team.
- [x] Example with the webworker skeleton. https://github.com/Yoast/YoastSEO.js/issues/1590
- [x] Implement a scheduler in the worker. https://github.com/Yoast/YoastSEO.js/issues/1617
- [x] Finish the example to actually do the analysis and show the results. https://github.com/Yoast/YoastSEO.js/issues/1620
- [x] Refactor callbacks inside the AnalysisWorker (Wrapper): QueuedItems class to have the flexibility to include more values like time, resolve, reject. https://github.com/Yoast/YoastSEO.js/issues/1618
- [x] Fix `window` reliance on markers (`hasMarker`). The worker should only return a list of `Mark` objects and these should be handled outside the web worker. (worker cannot access `window`). #1669
- [x] Use `removeHtmlBlocks` on the text in the worker (which is `stringProcessing/htmlParser.js`). https://github.com/Yoast/YoastSEO.js/issues/1673
- [x] Translations need to be sent to the worker. https://github.com/Yoast/YoastSEO.js/issues/1672
- [x] Change configuration to be global and local that merge before running an analysis. Assessor options in the worker: `useCornerStone`, `useKeywordDistribution`, `i18n`, `marker`, `locale`. https://github.com/Yoast/YoastSEO.js/issues/1657
- [x] Create an alternative to the `refresh` method in the plugin: uses other 2 points (collect the data & call analyze with the complete paper). https://github.com/Yoast/YoastSEO.js/issues/1677
- [x] Collect the data. Replacing or moving `getData`, `registerCustomDataCallback` and the Pluggable modifications. https://github.com/Yoast/YoastSEO.js/issues/1676
- [x] `registerAssessment` should be ported to work with `importScripts`. Check stories/web-worker-test for some test code. We need to prepend the base URL of the site to make `importScripts` a bit safer. By default, `importScripts` allows any URL, even from third parties. The script that is imported can then use an API that is provided by the code in the worker using `self.publicMethod = () => {}`. All our own add-ons that add a custom assessment need to be changed to accommodate this change. Add-ons that have a custom assessment: `video`, `local`, `woo`, `previouslyUsedKeywords`. https://github.com/Yoast/YoastSEO.js/issues/1680
- [x] Adapt custom assessment to `importScripts` version in `video`. https://github.com/Yoast/YoastSEO.js/issues/1681
- [x] Adapt custom assessment to `importScripts` version in `local`. https://github.com/Yoast/YoastSEO.js/issues/1682
- [x] Adapt custom assessment to `importScripts` version in `woo`. https://github.com/Yoast/YoastSEO.js/issues/1683
- [x] Adapt custom assessment to `importScripts` version in `previouslyUsedKeywords`. https://github.com/Yoast/YoastSEO.js/issues/1684
- [x] Move `Pluggable` to the plugin. Currently, all the add-ons integrate with `app.registerModification`. When we delete the `app` we need to backfill this method. Something like `YoastSEO.app = { registerModification: () => { /* register the modification with the moved pluggable here */ } };`. Things to be backfilled: `registerPlugin`, `pluginReady`, `pluginReloaded`, `registerModification`. https://github.com/Yoast/YoastSEO.js/issues/1678
- [x] Add markings to the results so that the plugin can access them. #1696
- [x] Change the plugin to use the markings in the results (from the store). https://github.com/Yoast/YoastSEO.js/issues/1692
- [x] Fix app usages that where not backfilled #1714

### Example
- [x] Implement localstorage for the example. https://github.com/Yoast/YoastSEO.js/issues/1619

### Stretch goals
- [x] Check if the Paper actually changed on the analyze request to prevent unnecessary initialization. https://github.com/Yoast/YoastSEO.js/issues/1658
- [x] AnalysisWorker (Wrapper) when done analyzing compare the results to the previous and only send the changes back in the promise resolve. https://github.com/Yoast/YoastSEO.js/issues/1659
- [x] Write tests for the worker. https://github.com/Yoast/YoastSEO.js/issues/1740
- [x] Investigate possibilities to deprecate separate locale configuration for ContentAssessor #1691
- [x] Backfill app usages in AssessorPresenters #1716
- [x] AnalysisWebWorker error with dev-server and Firefox #1728

### After release
- [x] Add a warning to the App indicating that it is deprecated. Something like `console.warn( "App in YoastSEO.js is no longer supported, please use the web worker instead. You can find documentation here: https://github.com/yoast/YoastSEO.js/docs/usage" );`. https://github.com/Yoast/YoastSEO.js/issues/1741

**Comment by atimmer** [comment]
Required for release holistically:

* Build the above MVP.
* Use the worker in the plugin.
* Fix `window` reliance in markers (`hasMarker`). The worker should only return a list of `Mark` objects and these should be handled outside the web worker. (worker cannot access `window`).
*

**Comment by igorschoester** [comment]
Only remaining is: https://yoast.atlassian.net/browse/LIN-170
