### ISSUE TITLE
Swedish module for readability analysis: overview issue

### ISSUE THREAD

**Issue by agnieszkaszuba** [Yoast/YoastSEO.js#1771]
Assessments for Swedish readability analysis (branch: feature/swedish):

- [x] Add Swedish transition word assessment #1770
- [x] Add Swedish internal linking #1797
- [x] Add Swedish internal linking in premium 
- [x] Add sentence length limit for Swedish #1906
- [x] Add sentence beginnings assessment #1944 
- [x] Add passive voice assessment for Swedish #1896 
- [x] Add Swedish to overview table in readme (changed in #1948)
