### ISSUE TITLE
YoastSEO.js development tool improvements - overview issue

### ISSUE THREAD

**Issue by manuelaugustin** [Yoast/YoastSEO.js#1963]
- [x] Use morphology data https://github.com/Yoast/YoastSEO.js/issues/1961
- [ ] Morphology data - switch between local/production data https://github.com/Yoast/YoastSEO.js/issues/1962
- [ ] Add language support for the morphology data loading
- [ ] Remove the old example https://github.com/Yoast/YoastSEO.js/issues/1941
- [x] Fix Jed error https://github.com/Yoast/YoastSEO.js/issues/1967
- [ ] Be able to filter assessments https://github.com/Yoast/YoastSEO.js/issues/1993
- [ ] Add an input field where you can enter a word, and an output field where you can instantly see the stem and all forms created for that word.
- [ ] Fix the example crashing when the `relevant words` tab is open, while the text is being removed (see https://github.com/Yoast/javascript/pull/7 for description).

**Comment by manuelaugustin** [comment]
The leftover points haven't been an issue recently. We will reopen issues if we find them necessary during development.
