### ISSUE TITLE
Overview: Cleanup App

### ISSUE THREAD

**Issue by igorschoester** [Yoast/YoastSEO.js#2045]
## Plugin deprecatation preparation
* [x] Deprecate `App` preperation: #1741 
  - [ ] Add console warning to the app: deprecated in favor of the analysis web worker: https://github.com/Yoast/YoastSEO.js/pull/2014
* [ ] Refactor `YoastReplaceVarPlugin` to not use `App`: https://github.com/Yoast/wordpress-seo/issues/11759
* [x] Refactor `YoastShortcodePlugin` to not use `App`: https://github.com/Yoast/wordpress-seo/issues/11760

## Deprecation
* [ ] Deprecate Pluggable:
  - Add console warning to pluggable: has been moved to the plugin.
* [ ] Deprecate SnippetPreview: needs-decision
  - Add console warning to the snippet preview: has been moved to yoast-components.
* [ ] Deprecate the presenters.
  - Add console warning to the presenters: will be removed.

## Remove
* [ ] Remove App.
* [ ] Remove Pluggable.
* [ ] Remove SnippetPreview: needs-decision
* [ ] Remove the presenters.

**Comment by nataliashitova** [comment]
After removing the App, please adjust the number of allowed eslint warnings, since now the App and its spec produce together 12 `require-jsdoc` warnings and 2 `complexity` warnings.

**Comment by igorschoester** [comment]
Moved to https://yoast.atlassian.net/browse/LIN-170
