### ISSUE TITLE
Improve German morphology

### ISSUE THREAD

**Issue by manuelaugustin** [Yoast/YoastSEO.js#2160]
The following parts of German morphology need to be improved:

## Stemming
- [ ] When a word ends in -ln, the -n should be removed to form the stem, see https://trello.com/c/7UA6WwVW/3-when-a-word-ends-in-ln-the-n-should-be-removed-to-form-the-stem
- [ ] If an -er suffix is preceded by i (but not ei), it should not be removed, see https://trello.com/c/reG8065O/5-if-an-er-suffix-is-preceded-by-i-but-not-ei-it-should-not-be-removed
- [ ] Add exceptions for nouns that are treated as compounds of irregular nouns, even though they're not (e.g. "Reisepass" is a compound of "Reise" + "Pass", but "Kompass" isn't a compound based on "Pass")
- Don't stem verbs -ern from verbs ending in -rn (e.g., "schildern") https://trello.com/c/dD3oja2P/15-find-solution-for-stemming-issue-for-verbs-ending-in-rn

## Verbs
- [x] Add functionality for German participles #2190 
- [x] Make sure that German words that have a vowel+e/i+vowel combination are stemmed correctly https://github.com/Yoast/javascript/pull/146
- [ ] Make sure that all irregular verbs are stemmed correctly https://github.com/Yoast/javascript/issues/163
- [x] Make sure that German verbs ending in -t are stemmed correctly https://github.com/Yoast/javascript/issues/189
- [ ] We can't correctly stem 3rd person singular verb forms ending in -t/-et for internal linking, see https://github.com/Yoast/javascript/pull/199
- [ ] Stem past participles with separable + inseparable prefix (e.g., "wiederentdecken") https://trello.com/c/3iGq0lgt/24-german-past-participle-stemming
- And more to come (see Lingo Research Trello board)
- Add affixes for verbs ending in -l or -n, see https://trello.com/c/tp6AW8cj/13-review-some-rules-for-possible-verb-suffixes

## Adjectives
https://github.com/Yoast/javascript/issues/236

Parent of #2190

Requires https://github.com/Yoast/YoastSEO.js-premium-configuration/issues/14

**Comment by nataliashitova** [comment]
While acceptance testing the basic functionality introduced in https://github.com/Yoast/YoastSEO.js/pull/2153 I've noticed a bunch of cases that don't work. In consultation with @manuelaugustin we decided that they should be addressed separately. 

### sein
`sein` > Personal forms, imperatives, past participle not recognized.
I failed to receive a full paradigm for any of the input forms. I realize that this word would not likely to be used as a keyphrase, but for consistency and future Linguistic Tree usages it can be more than beneficial to have a nice `sein`.

### haben
Verb forms are now generated using default (regular) rules. We need to add irregular forms, too.

###  verbs with separable prefixes
Verbs like `einkaufen` need special processing rules, which have not been implemented so far.

### schenken and similar
Not all verb forms are recognized. 
`schenkende` > Personal forms, imperatives, past participle not recognized.
`geschenkt` > No other forms are recognized.

**Comment by nataliashitova** [comment]
While working on https://github.com/Yoast/javascript/pull/210 I've noticed that the function `generateVerbExceptionFormsSpec` fails to generate the form `iss` from any of the stems of the verb `essen`. We should investigate how local this problem is (just for this verb, only for verbs whose stems end with `s`, only for verbs of class 4, etc.).

**Comment by manuelaugustin** [comment]
All open points moved here: https://yoast.atlassian.net/browse/LIN-577
