### ISSUE TITLE
Prerelease Checklist

### ISSUE THREAD

**Issue by omarreiss** [Yoast/YoastSEO.js#54]
* [x] Display issues in Firefox #51 
* [x] Snippet preview UX improvements #53 
* [x] Use a list instead of a table #49 
* [x] No newlines in snippet preview #48 
* [x] Don't submit the form when hitting enter #47 
* [x] Inaccessible bullets (add screenreader-text) #46 
* [x] Labels have no for attribute #45 
* [x] Error: linking to another page with the focus keyword #44 
* [x] Add diacritics #42
